@startuml diagram

object TrainGame

object Turns

object Player

object Train

object Track


TrainGame *-- Turns
TrainGame *-- Player
TrainGame *-- Train
TrainGame *-- Track

Turns -left-> Player
Turns -right-> Track
Player --> Train
Track --> Train

Train o-- TrainGoals
GAccelerate -up-|> TrainGoals
GStop -up-|> TrainGoals
GWhistle -up-|> TrainGoals

Train *-- Vagon:0..*
Principal -up-|> Vagon
Carga -up-|> Vagon
Pasajeros -up-|> Vagon
Train *-- Principal

Principal o-- ObjPrincipal
Accelerate -up-|> ObjPrincipal
Stop -up-|> ObjPrincipal
Whistle -up-|> ObjPrincipal

Vagon o-right- ObjVagon
MovementResistence --|> ObjVagon

Principal *-- Motor
Principal *-- WhistleArtifact





@enduml