@startuml dominio

object TicTacToe {
    Admin users
    Jugar TTT
    Mostrar estadisticas
    MEnu (usuario seleccione)
}

object AdminJugadores{
    Crear Jugador
    Listar jugador
    Seleccione dos jugadores 
}

object Partida{

}

object Estadisticas{

}

object Jugador{
    Ganar (lineas, columnas, diagon, diag invertida)
    seleccionarCoordenada
}

object Humano{
    seleccionarCoordenada 
    se solicita
}

object Computadora{
    seleccionarCoordenada
    pensar solita
}

object Tablero{

}

object Casilla{
    Vacio   0
    X       1
    O       2
}

object Coordenada{
    X
    Y
}

TicTacToe *-- AdminJugadores
TicTacToe *-- Partida
TicTacToe *-- Estadisticas

AdminJugadores *-- Jugador:*

Humano -up-|> Jugador
Computadora -up-|> Jugador

Partida -left-> AdminJugadores:pedir2jugadores
Partida *-- Jugador:2

Partida *-- Tablero

Tablero *-- Casilla:3x3

Casilla *-- Coordenada

Jugador ..> Coordenada: pongaFicha

Jugador o-- Casilla

Partida -right-> Estadisticas



@enduml